org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Low-memory machines (<=2GB): uncomment the following:
# org.gradle.workers.max=1
# kotlin.compiler.execution.strategy=in-process
# kotlin.daemon.jvmargs=-Xmx768m
