FEATURE_REGISTRY = [
    {
        "feature_id": "WIN_WIFI_STATUS",
        "category": "Windows",
        "natural_language_examples": ["show wifi status", "what wifi am i on", "is wifi connected"],
        "implementation_module": "tools.network.get_wifi_status",
        "safety_level": "low",
        "dependency": "Windows networking API",
        "test_method": "netsh wlan show interfaces",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_WIFI_TOGGLE",
        "category": "Windows",
        "natural_language_examples": ["turn wifi on", "turn wifi off", "disable wifi"],
        "implementation_module": "tools.network.toggle_wifi",
        "safety_level": "medium",
        "dependency": "Windows adapter control",
        "test_method": "Get-NetAdapter and netsh",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_WIFI_LIST_NETWORKS",
        "category": "Windows",
        "natural_language_examples": ["show available networks", "list wifi networks"],
        "implementation_module": "tools.system.list_wifi_networks",
        "safety_level": "low",
        "dependency": "Windows Wi-Fi profile API",
        "test_method": "netsh wlan show networks mode=Bssid",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_BLUETOOTH_STATUS",
        "category": "Windows",
        "natural_language_examples": ["is bluetooth on", "show bluetooth"],
        "implementation_module": "tools.bluetooth.get_bluetooth_status",
        "safety_level": "low",
        "dependency": "Windows Bluetooth adapter enumeration",
        "test_method": "Get-PnpDevice -Class Bluetooth",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_BLUETOOTH_TOGGLE",
        "category": "Windows",
        "natural_language_examples": ["turn bluetooth on", "turn bluetooth off"],
        "implementation_module": "tools.bluetooth.toggle_bluetooth",
        "safety_level": "medium",
        "dependency": "Windows PnP Bluetooth control",
        "test_method": "Enable-PnpDevice / Disable-PnpDevice",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_BLUETOOTH_LIST_DEVICES",
        "category": "Windows",
        "natural_language_examples": ["show bluetooth devices", "what devices are paired"],
        "implementation_module": "tools.system.list_bluetooth_devices",
        "safety_level": "low",
        "dependency": "Windows Bluetooth adapter metadata",
        "test_method": "Get-PnpDevice -Class Bluetooth",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_AUDIO_VOLUME",
        "category": "Windows",
        "natural_language_examples": ["volume up", "mute", "unmute"],
        "implementation_module": "tools.media",
        "safety_level": "low",
        "dependency": "Windows audio session API",
        "test_method": "volume control smoke test",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_DISPLAY_BRIGHTNESS",
        "category": "Windows",
        "natural_language_examples": ["brightness up", "set brightness to 60"],
        "implementation_module": "tools.display.set_brightness",
        "safety_level": "low",
        "dependency": "Windows brightness API",
        "test_method": "PowerShell Wmi brightness APIs",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_NETWORK_INFO",
        "category": "Windows",
        "natural_language_examples": ["network info", "what is my ip", "show network status"],
        "implementation_module": "tools.network.get_network_information",
        "safety_level": "low",
        "dependency": "Windows networking APIs",
        "test_method": "Get-NetIPAddress and Get-NetAdapter",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_STORAGE_INFO",
        "category": "Windows",
        "natural_language_examples": ["disk usage", "show free space"],
        "implementation_module": "tools.system.get_storage_remaining",
        "safety_level": "low",
        "dependency": "Windows disk APIs",
        "test_method": "DriveInfo and PowerShell disk checks",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "WIN_SETTINGS_NAVIGATION",
        "category": "Windows",
        "natural_language_examples": ["open settings", "open display settings", "task manager"],
        "implementation_module": "tools.system.open_settings",
        "safety_level": "low",
        "dependency": "Windows URI and shell launch",
        "test_method": "os.startfile and subprocess",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "FILE_CREATE_RENAME_DELETE",
        "category": "Files",
        "natural_language_examples": ["create file", "rename this file", "delete file"],
        "implementation_module": "tools.file_manager",
        "safety_level": "medium",
        "dependency": "Windows filesystem access",
        "test_method": "safe file workspace smoke tests",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "FILE_COPY_MOVE",
        "category": "Files",
        "natural_language_examples": ["copy this file", "move this folder"],
        "implementation_module": "tools.file_manager.copy_file",
        "safety_level": "medium",
        "dependency": "Filesystem access",
        "test_method": "workspace copy/move flow",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "BROWSER_CDP",
        "category": "Browser",
        "natural_language_examples": ["open browser", "search google", "open url"],
        "implementation_module": "tools.browser",
        "safety_level": "low",
        "dependency": "Brave + CDP",
        "test_method": "browser CDP smoke test",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "YOUTUBE_MEDIA",
        "category": "Browser",
        "natural_language_examples": ["search youtube", "play youtube", "pause video"],
        "implementation_module": "tools.youtube",
        "safety_level": "low",
        "dependency": "Brave CDP + live YouTube page",
        "test_method": "live YouTube tab control",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "SPOTIFY_MEDIA",
        "category": "Browser",
        "natural_language_examples": ["play spotify", "next song", "pause spotify"],
        "implementation_module": "tools.spotify",
        "safety_level": "low",
        "dependency": "Brave CDP + Spotify web app",
        "test_method": "live Spotify tab control",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "ANDROID_DEVICE_PROTOCOL",
        "category": "Android",
        "natural_language_examples": ["show my phone status", "send this to my Android"],
        "implementation_module": "AlfredAndroid app websocket + agent",
        "safety_level": "low",
        "dependency": "Android device + companion app",
        "test_method": "local protocol mock / live device pairing",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
    {
        "feature_id": "VOICE_PIPELINE",
        "category": "Voice",
        "natural_language_examples": ["wake word", "record command", "transcribe this"],
        "implementation_module": "main.py + voice/*",
        "safety_level": "low",
        "dependency": "microphone + TTS + STT stack",
        "test_method": "live microphone session",
        "status": "IMPLEMENTED_AWAITING_TEST",
    },
]


def get_feature_registry():
    return FEATURE_REGISTRY


def summarize_registry():
    counts = {status: 0 for status in ["PASS", "FAIL", "NOT_IMPLEMENTED", "MANUAL", "DEPENDENCY", "SKIPPED", "IMPLEMENTED_AWAITING_TEST"]}
    for feature in FEATURE_REGISTRY:
        counts[feature["status"]] = counts.get(feature["status"], 0) + 1
    return counts
